language: python

python:
  - "3.6"

service:
  - postgresql

install:
  - pip install -r requirements.txt

test:
  adapter: postgresql

before_script:
  - export APP_SETTINGS="project.config.DevelopmentConfig"
  - export DATABASE_TEST_URL=postgresql://postgres:@localhost/users_dev
  - psql -c 'create database users_test;' -U postgres
  - python manager.py recreate_db

script:
  - python manager.py test